name: Ensure CI image

on:
  workflow_dispatch:

env:
  IMAGE_REGISTRY: ghcr.io
  CI_DOCKERFILE_DIR: ./ci # Relative to project root
  CI_DOCKERFILE_PATH: Dockerfile # Relative to CI_DOCKERFILE_DIR
  CI_DOCKERFILE_MOST_RECENT_SHA: # Determined dynamically later on

jobs:
  calculate-latest-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Calculate label for CI image
      env:
        IMAGE_NAME: ${{ github.repository }}
      run: |
        dockerfile_path=${CI_DOCKERFILE_DIR}/${CI_DOCKERFILE_PATH}

        [[ ! -f ${dockerfile_path} ]] && echo "Could not find Dockerfile at ${dockerfile_path}" && exit 1

        echo "CI_DOCKERFILE_MOST_RECENT_SHA=$(git log --pretty=format:%H "${dockerfile_path}")" >> $GITHUB_ENV
        cat "${GITHUB_ENV}"

    - name: Login to GitHub container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      uses: docker/metadata-action@v5
      id: meta
      with:
        images: ${{ env.IMAGE_REGISTRY }}/${{ github.repository }}
        # tags: |
        #   ${{ env.CI_DOCKERFILE_MOST_RECENT_SHA }}
        #   ${{ github.ref_name }}-latest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push CI image
      uses: docker/build-push-action@v5
      with:
        push: true
        context: ${{ env.CI_DOCKERFILE_DIR }}
        file: ${{ env.CI_DOCKERFILE_DIR }}/${{ env.CI_DOCKERFILE_PATH }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}