name: Check token scope
on:
  workflow_dispatch:
  push:

jobs:
  check-token:
    runs-on: ubuntu-latest
    steps:
    - name: print env
      run: |
        env | sort
    - name: print token
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        sudo apt update
        sudo apt install gh --yes
        gh auth status